using DungeonSiegeLab.Models;
using DungeonSiegeLab.Patterns;
using ImageMagick;

namespace DungeonSiegeLab.Services;

// ============================================================
// FACADE PATTERN
// RawTextureConverter skrýva komplexnosť konverzie textúr
// (Strategy výber, RawToPsd volanie, Magick.NET, RAW generácia)
// za jednoduché metódy.
// ============================================================

public class RawTextureConverter
{
    private readonly TextureProcessorFactory _processorFactory = new();
    private string _rawToPsdToolPath = "";

    public void SetToolPath(string path) => _rawToPsdToolPath = path;

    /// <summary>Načíta textúru, konvertuje na PNG a vráti LoadedTexture.</summary>
    public async Task<LoadedTexture> LoadTextureAsync(TextureReference textureRef)
    {
        if (textureRef.ResolvedPath is null)
            throw new FileNotFoundException($"Textúra '{textureRef.TextureName}' nebola nájdená v /Bits.");

        return await LoadFromPathAsync(textureRef.TextureName, textureRef.ResolvedPath);
    }

    public async Task<LoadedTexture> LoadFromPathAsync(string name, string filePath)
    {
        var processor = _processorFactory.GetProcessor(filePath);
        var pngPath = await processor.ConvertToPngAsync(filePath, _rawToPsdToolPath);
        var (w, h) = await processor.GetDimensionsAsync(filePath, _rawToPsdToolPath);

        return new LoadedTexture
        {
            Name = name,
            OriginalPath = filePath,
            PngCachePath = pngPath,
            Width = w,
            Height = h
        };
    }

    /// <summary>
    /// Exportuje PNG textúru na disk (Save to disk as...).
    /// </summary>
    public async Task ExportToDiskAsync(LoadedTexture texture, string targetPath)
    {
        if (texture.PngCachePath is null)
            throw new InvalidOperationException("Textúra nie je načítaná.");

        await Task.Run(() => File.Copy(texture.PngCachePath, targetPath, overwrite: true));
    }

    /// <summary>
    /// Uloží textúru do projektu (Save to project as...).
    /// Konvertuje PNG → RAW a vygeneruje .gas súbor.
    /// </summary>
    public async Task SaveToProjectAsync(LoadedTexture texture, string bitsRootPath,
        string relativePath, string textureName)
    {
        var targetDir = Path.Combine(bitsRootPath, relativePath);
        Directory.CreateDirectory(targetDir);

        var rawPath = Path.Combine(targetDir, textureName + ".raw");
        var gasPath = Path.Combine(targetDir, textureName + ".gas");

        // Konvertuj PNG → RAW (via Magick.NET — raw bytes)
        await Task.Run(() =>
        {
            if (texture.PngCachePath is null) return;
            using var image = new MagickImage(texture.PngCachePath);
            // DS raw je 32-bit BGRA; toto je zjednodušená konverzia
            image.Format = MagickFormat.Rgba;
            image.Write(rawPath);
        });

        // Vygeneruj minimálny .gas súbor pre textúru
        var gasContent = GenerateTextureGas(textureName, relativePath);
        await File.WriteAllTextAsync(gasPath, gasContent);
    }

    /// <summary>
    /// Importuje náhradnú textúru (Import replacement).
    /// </summary>
    public async Task<LoadedTexture> ImportReplacementAsync(string pngPath, string originalName)
    {
        return await LoadFromPathAsync(originalName, pngPath);
    }

    private static string GenerateTextureGas(string name, string path) =>
        $$"""
        // Auto-generated by DungeonSiegeLab
        [t:template,n:{{name}}]
        {
            [aspect]
            {
                [textures]
                {
                    0 = {{name}};
                }
            }
        }
        """;
}
